apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-ansa
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/rycole-appstudio/integration1-pslh-tenant/integ-app-dtxk/hacbs-test-project-ansa@sha256:60f8630c126d1bf841147249525c1973a9be9d8feca8baf30027be0bc2f761f8
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
